version: '3'
services:
  flask_local_server:
    image: flask_local_server
    build:
      context: .
      dockerfile: ./flask_local_server/Dockerfile
    networks:
      - test
    container_name: flask_local_server
    command: flask --app flaskr --debug run --host=0.0.0.0
    working_dir: /opt
    ports:
      - "5000:5000"
    volumes:
      - ./flaskr:/opt/flaskr
  flask-pytest:
    container_name: pytest
    image: flask_local_server
    # command: ping host.docker.internal
    command: pytest -s flaskr
    working_dir: /opt
    volumes:
      - ./flaskr:/opt/flaskr
    depends_on:
      - flask_local_server
    networks:
      - test
networks:
  test:
    driver: bridge
